#!/bin/bash

. "$(dirname "$0")/config.sh"

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
  echo "Delete Reports menus"
  issabel-menuremove "reports"

  echo "Dump and delete issabel-reports databases"
  issabel-dbprocess "delete" "$pathModule/setup/db"
fi

rm -rf /usr/share/issabel/module_installer/${folderName}
rm -rf /var/www/html/modules

echo 'Issabel Reports Removed Sucessfully'

exit 0

