#!/bin/bash

. /usr/share/issabel-reports/vars

mkdir -p /usr/share/issabel/module_installer/${folderName}/
mkdir -p /var/www/html/libs/

pathSQLiteDB="/var/www/db"
mkdir -p $pathSQLiteDB

chmod -R 755 /modules/
chmod -R 755 /setup/
chown -R root:root /modules/
chown -R root:root /setup/

pathModule="/usr/share/issabel/module_installer/$folderName"
mv /modules/ /var/www/html/
mv /setup/paloSantoCDR.class.php      /var/www/html/libs/
mv /setup/paloSantoTrunk.class.php    /var/www/html/libs/
mv /setup/paloSantoRate.class.php     /var/www/html/libs/
mv /setup/paloSantoQueue.class.php    /var/www/html/libs/
mv /setup/menu.xml                    /usr/share/issabel/module_installer/${folderName}/
mv /setup/                            /usr/share/issabel/module_installer/${folderName}/

issabel-menumerge /usr/share/issabel/module_installer/${folderName}/menu.xml
issabel-dbprocess "install" "$pathModule/setup/db"

mkdir -p /tmp/new_module/${packageName}
cp -r /usr/share/issabel/module_installer/${folderName}/* /tmp/new_module/${packageName}/
chown -R asterisk.asterisk /tmp/new_module/${packageName}
php /tmp/new_module/${packageName}/setup/installer.php

echo $packageFriendlyName 'Installed successfully, Cleaning up...'

# cleanup
rm -rf /tmp/new_module/${packageName}
