#!/bin/bash

. "$(dirname "$0")/config.sh"

echo $packageFriendlyName 'Installing ...'
mkdir -p /var/www/html/libs/
mkdir -p /usr/share/issabel/module_installer/${folderName}/

pathSQLiteDB="/var/www/db"
mkdir -p $pathSQLiteDB
