#!/bin/bash

export packageFriendlyName="Issabel Reports"
export packageName="issabel-reports"
export version="VERSION_NUMBER"
export release="RELEASE_NUMBER"
export fullVersionName="$version-$release"
export folderName="$packageName-$fullVersionName"
